### ISSUE TITLE
可以分享一下爬数据的代码么

### ISSUE THREAD

**Issue by zhenduow** [dfbb/WclPlayerScore#2]
你好，我在美服玩，我看了你的代码，发现数据都存在静态的文件里，所以我想自己添加我们服务器的数据，然后分享给公会的人使用，请问可以分享一下爬数据的代码么？

**Comment by dfbb** [comment]
马上就有美服版本了，叫 iWclPlayerScore

**Comment by dfbb** [comment]
https://www.curseforge.com/wow/addons/iwclplayerscore/
